from enum import Enum


class DownloadStatus(Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    TIMEOUT = "TIMEOUT"
    ERROR = "ERROR"
    TOO_LARGE = "TOO_LARGE"
    INVALID_TORRENT = "INVALID_TORRENT"


class SonicBitStatus(Enum):
    IDLE = "IDLE"
    PROCESSING = "PROCESSING"
    DOWNLOADING = "DOWNLOADING"
    LOCKED = "LOCKED"
    UPLOADING = "UPLOADING"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"
